### ISSUE TITLE
Could you please provide the NeRF ckpt files corresponding to the released mesh results of all prompt sets and methods?

### ISSUE THREAD

**Issue by Clear-3d** [THU-LYJ-Lab/T3Bench#8]
Hello! Thank you for this fantastic work. Could you please provide the NeRF ckpt files corresponding to the released mesh results of all prompt sets and methods? I've noticed a significant drop in rendering quality after mesh extraction. I'm very interested in their results and would like to test and compare their performance.

**Comment by hyz317** [comment]
Hi,

We understand your interest in the NeRF ckpt files corresponding to the mesh results. Unfortunately, due to their large file size, we are unable to upload them directly. We encourage you to reproduce the results yourself, as this allows for greater flexibility and control over the experiment.

It's also important to note that the quality of the mesh extraction often reflects the inherent geometry of the generated 3D result. In cases where the extracted mesh exhibits lower quality, it often signifies that the underlying NeRF model itself struggled to produce precise geometry.

**Comment by Clear-3d** [comment]
I see. Thank you for your patient reply!
